import React, { useState } from 'react';
import {
  Sparkles,
  Award,
  CheckCircle2,
  FileText,
  Target,
  Layers,
  ChevronRight,
  RefreshCw,
  Check,
  X,
  Bot,
  Zap,
} from 'lucide-react';
import {
  careerApi,
  ChatMessage,
  InterviewEvaluation,
  AiStatus,
} from '../../api';
import { HiddenStrengthsDashboard } from './HiddenStrengthsDashboard';
import { EvidenceDetailModal } from './EvidenceDetailModal';
import { ResumeApprovalModal } from './ResumeApprovalModal';
import {
  HiddenStrength,
  sampleHiddenStrengths,
} from '../../data/hiddenStrengthsData';

interface ResumeIntelligenceProps {
  initialTab?: 'score' | 'hidden-strengths' | 'ats' | 'improvements' | 'role-based' | 'versions';
  go: (page: any) => void;
  act: (msg: string, inc?: number) => void;
}

export const ResumeIntelligence: React.FC<ResumeIntelligenceProps> = ({
  initialTab = 'score',
  go,
  act,
}) => {
  const [activeTab, setActiveTab] = useState<
    'score' | 'hidden-strengths' | 'ats' | 'improvements' | 'role-based' | 'versions'
  >(initialTab);

  const [companyPromptOpen, setCompanyPromptOpen] = useState(false);
  const [companyInput, setCompanyInput] = useState('');
  const [company, setCompany] = useState('TechNova');
  const [tailored, setTailored] = useState(false);
  const [isTailoring, setIsTailoring] = useState(false);
  const [tailorExplanation, setTailorExplanation] = useState('');
  const [aiProvider, setAiProvider] = useState<'gemini' | 'mock'>('gemini');

  const [resumeMode, setResumeMode] = useState<
    'general' | 'improve' | 'concise' | 'keywords' | 'quantify' | 'company'
  >('general');

  const [experienceOne, setExperienceOne] = useState(
    'Built a full-stack learning platform using React, TypeScript, and Node.js. Implemented user authentication and dynamic dashboard features for 500+ active users.'
  );
  const [experienceTwo, setExperienceTwo] = useState(
    'Developed a real-time attendance system with QR code scanning and automated reporting, reducing administrative overhead by 40%.'
  );
  const [skillsText, setSkillsText] = useState(
    'Python · React · Node.js · SQL · REST APIs · Docker · Git · Data Structures'
  );
  const [missingText, setMissingText] = useState(
    'GraphQL · Kubernetes · System Design (Recommended for senior roles)'
  );

  const [metrics, setMetrics] = useState({
    jobMatch: 82,
    atsScore: 78,
    keywordCoverage: 74,
  });

  // Hidden Strengths modal states
  const [selectedEvidenceStrength, setSelectedEvidenceStrength] = useState<HiddenStrength | null>(null);
  const [selectedApprovalStrength, setSelectedApprovalStrength] = useState<HiddenStrength | null>(null);

  const handleAction = async (action: string) => {
    if (action === 'Tailor for target company') {
      setCompanyPromptOpen(true);
      return;
    }
    const modeMap: Record<string, 'improve' | 'concise' | 'keywords' | 'quantify' | 'company'> = {
      'Improve bullet point': 'improve',
      'Make more concise': 'concise',
      'Add relevant keywords': 'keywords',
      'Quantify impact': 'quantify',
    };

    const targetAction = modeMap[action] || 'improve';
    setResumeMode(targetAction);
    setIsTailoring(true);

    try {
      const res = await careerApi.tailorResumeBullet({
        bulletText: experienceOne,
        action: targetAction,
        targetCompany: company || undefined,
      });
      setExperienceOne(res.rewrittenText);
      setTailorExplanation(res.explanation);
      setAiProvider(res.provider);

      if (targetAction === 'keywords') {
        setSkillsText('Python · React · Node.js · SQL · REST APIs · Docker · Git · Data Structures');
        setMissingText('✓ Added relevant keywords for backend and fullstack roles');
      } else if (targetAction === 'quantify') {
        setMissingText('✓ Quantified impact with performance metrics');
      }

      act(`${action} generated by ${res.provider === 'gemini' ? 'Gemini LLM' : 'AI'}`, 20);
    } catch {
      act(`${action} applied to your resume`, 20);
    } finally {
      setIsTailoring(false);
    }
  };

  const submitCompany = async (e: React.FormEvent) => {
    e.preventDefault();
    const name = companyInput.trim() || 'TechNova';
    setTailored(true);
    setCompany(name);
    setResumeMode('company');
    setCompanyPromptOpen(false);
    setIsTailoring(true);

    try {
      const res = await careerApi.tailorResumeBullet({
        bulletText: experienceOne,
        action: 'company',
        targetCompany: name,
      });
      setExperienceOne(res.rewrittenText);
      setTailorExplanation(res.explanation);
      setAiProvider(res.provider);
      setSkillsText(`Python · React · Node.js · SQL · REST APIs · Docker · ${name} fit`);
      setMissingText(`✓ Aligned to ${name} engineering stack`);
      act(`Resume tailored for ${name} using ${res.provider === 'gemini' ? 'Gemini LLM' : 'Mock AI'}`, 50);
    } catch {
      act(`Resume tailored for ${name}`, 50);
    } finally {
      setIsTailoring(false);
    }
  };

  const generateTargetedResume = async () => {
    setIsTailoring(true);
    try {
      const analysis = await careerApi.analyzeResume({
        resumeContent: `${experienceOne}\n${experienceTwo}\n${skillsText}`,
        companyName: company || 'TechNova',
      });
      setMetrics({
        jobMatch: analysis.jobMatchScore,
        atsScore: analysis.atsScore,
        keywordCoverage: analysis.keywordScore,
      });
      setAiProvider(analysis.provider);
      act(`Targeted resume analyzed (${analysis.atsScore}% ATS score)`, 50);
    } catch {
      act('Targeted resume generated', 50);
    } finally {
      setIsTailoring(false);
    }
  };

  const handleApplyApprovedStrength = (bullet: string, summary: string) => {
    setExperienceOne(bullet);
    setTailorExplanation('Updated with verified Hidden Strength wording.');
    setMetrics((prev) => ({
      ...prev,
      atsScore: Math.min(95, prev.atsScore + 6),
      jobMatch: Math.min(96, prev.jobMatch + 5),
    }));
  };

  const versionPills = [
    { label: 'General Resume', mode: 'general' },
    { label: 'Software Engineer Resume', mode: 'improve' },
    {
      label: tailored ? `${company} Resume` : 'Company Resume',
      mode: tailored ? 'company' : 'general',
    },
  ];

  return (
    <div className="resumeIntelligenceContainer">
      {/* Segmented Sub-Navigation Tabs */}
      <div className="networkTopTabsBar">
        {[
          { key: 'score', label: 'Resume Score & Editor', icon: FileText },
          { key: 'hidden-strengths', label: 'Hidden Strengths (5)', icon: Sparkles },
          { key: 'ats', label: 'ATS Alignment', icon: Target },
          { key: 'improvements', label: 'Resume Improvements', icon: Zap },
          { key: 'role-based', label: 'Role-Based Resume', icon: Award },
          { key: 'versions', label: 'Resume Versions', icon: Layers },
        ].map(({ key, label, icon: Icon }) => (
          <button
            key={key}
            className={`networkTabBtn ${activeTab === key ? 'networkTabActive' : ''}`}
            onClick={() => {
              setActiveTab(key as any);
              act(`Resume Intelligence: Switched to ${label}`, 5);
            }}
          >
            <Icon size={15} />
            <span>{label}</span>
          </button>
        ))}
      </div>

      {/* Main Tab Content */}
      <div className="resumeTabContent">
        {/* TAB 1: RESUME SCORE & EDITOR (Existing Implementation) */}
        {activeTab === 'score' && (
          <>
            <div className="titleRow">
              <div>
                <p className="eyebrow">RESUME INTELLIGENCE</p>
                <h1>Turn your experience into signal</h1>
                <p className="muted">A precise, role-aware review of your resume powered by Gemini LLM.</p>
              </div>
              <button
                className="primary"
                onClick={generateTargetedResume}
                disabled={isTailoring}
              >
                {isTailoring ? <RefreshCw size={14} className="aiSpin" /> : <Sparkles size={14} />}
                {isTailoring ? 'Analyzing...' : 'Generate targeted resume'}
              </button>
            </div>

            <div className="resumeLayout">
              <div className="card resumePaper">
                <div className="resumeName">DIVYA</div>
                <p>
                  Software Engineer Candidate
                  {tailored && <> · Tailored for {company}</>}
                </p>
                <hr />
                <b>EXPERIENCE</b>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 14 }}>
                  <h4 style={{ margin: 0 }}>Placement Analytics & Checkout Dashboard</h4>
                  {tailorExplanation && (
                    <span className={`aiBadge ${aiProvider === 'gemini' ? 'active' : 'mock'}`} style={{ fontSize: 9 }}>
                      {aiProvider === 'gemini' ? 'Gemini Rewritten' : 'AI Mode'}
                    </span>
                  )}
                </div>
                <p style={{ marginTop: 4 }}>{experienceOne}</p>
                {tailorExplanation && (
                  <small style={{ display: 'block', color: '#8b7cff', fontStyle: 'italic', marginBottom: 8 }}>
                    💡 {tailorExplanation}
                  </small>
                )}
                <h4>Smart Attendance System</h4>
                <p>{experienceTwo}</p>
                <hr />
                <b>SKILLS</b>
                <p>{skillsText}</p>
                {tailored && (
                  <>
                    <hr />
                    <b>TARGET COMPANY</b>
                    <p>{company}</p>
                  </>
                )}
              </div>

              <div>
                <div className="card" style={{ marginBottom: 14 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span className="pill purple">
                      <Sparkles size={14} /> AI RESUME INTELLIGENCE
                    </span>
                    <span className={`aiBadge ${aiProvider === 'gemini' ? 'active' : 'mock'}`}>
                      {aiProvider === 'gemini' ? 'Gemini 2.5 Flash' : 'Smart Mock'}
                    </span>
                  </div>
                  <div className="resumeMetrics" style={{ margin: '14px 0' }}>
                    {[
                      [`${metrics.jobMatch}%`, 'Job Match'],
                      [`${metrics.atsScore}%`, 'ATS Compatibility'],
                      [`${metrics.keywordCoverage}%`, 'Keyword Coverage'],
                    ].map((x) => (
                      <div key={x[1]}>
                        <b>{x[0]}</b>
                        <span>{x[1]}</span>
                      </div>
                    ))}
                  </div>
                  <h4>Strengths</h4>
                  <p className="checks">
                    <Check size={14} /> Python <Check size={14} /> React.js <Check size={14} /> Vitest Tests
                  </p>
                  <h4>Missing keywords</h4>
                  <p className="warn">{missingText}</p>
                </div>

                <div className="card" style={{ marginBottom: 14 }}>
                  <h3>AI actions</h3>
                  {[
                    'Improve bullet point',
                    'Make more concise',
                    'Add relevant keywords',
                    'Quantify impact',
                    'Tailor for target company',
                  ].map((x) => (
                    <button
                      className="actionButton"
                      onClick={() => handleAction(x)}
                      key={x}
                      disabled={isTailoring}
                      style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        width: '100%',
                        padding: '10px 12px',
                        background: '#131520',
                        border: '1px solid #282f42',
                        borderRadius: 8,
                        color: '#edf0f8',
                        marginBottom: 8,
                        cursor: 'pointer',
                      }}
                    >
                      <span>{x}</span>
                      <ChevronRight size={16} />
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </>
        )}

        {/* TAB 2: HIDDEN STRENGTHS DASHBOARD (New Feature) */}
        {activeTab === 'hidden-strengths' && (
          <HiddenStrengthsDashboard
            onOpenEvidenceDetail={(s) => setSelectedEvidenceStrength(s)}
            onOpenResumeApproval={(s) => setSelectedApprovalStrength(s)}
            act={act}
          />
        )}

        {/* TAB 3: ATS ALIGNMENT */}
        {activeTab === 'ats' && (
          <div className="card" style={{ padding: 20 }}>
            <div className="cardTop" style={{ marginBottom: 12 }}>
              <h2 style={{ margin: 0 }}>ATS Compatibility & Keyword Matching</h2>
              <span className="pill green">{metrics.atsScore}% Overall Match</span>
            </div>
            <p className="muted" style={{ marginBottom: 16 }}>
              Your resume matches the core technical stack for Junior Frontend and Full Stack developer job requisitions.
            </p>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
              <div style={{ background: '#131520', padding: 14, borderRadius: 8 }}>
                <b style={{ color: '#86e5b1', display: 'block', marginBottom: 6 }}>✓ Matched Stack Keywords</b>
                <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                  {['React', 'TypeScript', 'Node.js', 'SQL', 'Vitest', 'REST APIs', 'Git'].map((k) => (
                    <span key={k} className="pill green" style={{ fontSize: 9 }}>{k}</span>
                  ))}
                </div>
              </div>
              <div style={{ background: '#131520', padding: 14, borderRadius: 8 }}>
                <b style={{ color: '#ffd175', display: 'block', marginBottom: 6 }}>⚡ High-Value Recommended Keywords</b>
                <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                  {['GraphQL', 'CI/CD Pipelines', 'Docker', 'Web Accessibility'].map((k) => (
                    <span key={k} className="pill orange" style={{ fontSize: 9 }}>{k}</span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 4: RESUME IMPROVEMENTS */}
        {activeTab === 'improvements' && (
          <div className="card" style={{ padding: 20 }}>
            <h2 style={{ margin: '0 0 10px' }}>AI-Powered Bullet Point Improvements</h2>
            <p className="muted" style={{ marginBottom: 16 }}>
              Select any bullet point from your resume to enhance impact, quantify results, and inject active verbs.
            </p>
            <div style={{ background: '#131520', padding: 14, borderRadius: 8, marginBottom: 14 }}>
              <small style={{ color: '#8e96a8', display: 'block', marginBottom: 4 }}>Current Active Bullet:</small>
              <p style={{ fontSize: 13, color: '#f0edff', margin: 0 }}>"{experienceOne}"</p>
            </div>
            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
              <button className="primary" onClick={() => handleAction('Quantify impact')} disabled={isTailoring}>
                Quantify Metrics (+20 XP)
              </button>
              <button className="secondary" onClick={() => handleAction('Make more concise')} disabled={isTailoring}>
                Make More Concise
              </button>
              <button className="secondary" onClick={() => handleAction('Add relevant keywords')} disabled={isTailoring}>
                Inject Keyword Stack
              </button>
            </div>
          </div>
        )}

        {/* TAB 5: ROLE-BASED TAILORING */}
        {activeTab === 'role-based' && (
          <div className="card" style={{ padding: 20 }}>
            <h2 style={{ margin: '0 0 10px' }}>Target Company & Role Tailoring</h2>
            <p className="muted" style={{ marginBottom: 16 }}>
              Align your resume language and highlighted projects specifically for your target company.
            </p>
            <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
              <button className="primary" onClick={() => setCompanyPromptOpen(true)}>
                <Target size={14} /> Tailor Resume for Company ({company})
              </button>
            </div>
          </div>
        )}

        {/* TAB 6: RESUME VERSIONS */}
        {activeTab === 'versions' && (
          <div className="card" style={{ padding: 20 }}>
            <h2 style={{ margin: '0 0 10px' }}>Saved Resume Versions (3)</h2>
            <div style={{ display: 'grid', gap: 10, marginTop: 14 }}>
              {versionPills.map((v) => (
                <div
                  key={v.label}
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    background: '#131520',
                    padding: '12px 16px',
                    borderRadius: 8,
                    border: '1px solid #282f42',
                  }}
                >
                  <div>
                    <b style={{ fontSize: 13 }}>{v.label}</b>
                    <small style={{ display: 'block', color: '#8e96a8', marginTop: 2 }}>
                      ATS Score: 88% · Last updated: August 2026
                    </small>
                  </div>
                  <button className="secondary" onClick={() => setActiveTab('score')}>
                    Open in Editor
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Company Prompt Modal */}
      {companyPromptOpen && (
        <div className="profileModalOverlay" onClick={() => setCompanyPromptOpen(false)}>
          <form
            className="profileModal"
            onSubmit={submitCompany}
            onClick={(event) => event.stopPropagation()}
          >
            <div className="profileModalHeader">
              <div>
                <p className="eyebrow">RESUME TAILORING</p>
                <h2>Choose a target company</h2>
              </div>
              <button
                type="button"
                className="icon"
                onClick={() => setCompanyPromptOpen(false)}
                aria-label="Close company prompt"
              >
                <X size={18} />
              </button>
            </div>
            <label className="profileField">
              <span>Company name</span>
              <input
                autoFocus
                value={companyInput}
                onChange={(event) => setCompanyInput(event.target.value)}
                placeholder="e.g. Google, Microsoft, TechNova, Razorpay"
              />
            </label>
            <div className="profileActions">
              <button
                type="button"
                className="secondary"
                onClick={() => setCompanyPromptOpen(false)}
              >
                Cancel
              </button>
              <button className="primary" type="submit" disabled={isTailoring}>
                {isTailoring ? 'Tailoring...' : 'Tailor bullet'}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* EVIDENCE DETAIL MODAL */}
      {selectedEvidenceStrength && (
        <EvidenceDetailModal
          strength={selectedEvidenceStrength}
          onClose={() => setSelectedEvidenceStrength(null)}
          onOpenResumeApproval={(s) => {
            setSelectedEvidenceStrength(null);
            setSelectedApprovalStrength(s);
          }}
          onHideStrength={(id) => {
            setSelectedEvidenceStrength(null);
            act('Strength hidden from dashboard');
          }}
          onMarkInaccurate={(id) => {
            setSelectedEvidenceStrength(null);
            act('Marked as inaccurate. CareerOS will recalibrate');
          }}
          act={act}
        />
      )}

      {/* RESUME APPROVAL MODAL */}
      {selectedApprovalStrength && (
        <ResumeApprovalModal
          strength={selectedApprovalStrength}
          onClose={() => setSelectedApprovalStrength(null)}
          onApplyToResume={handleApplyApprovedStrength}
          act={act}
        />
      )}
    </div>
  );
};
